import type { Metadata, Viewport } from "next";
import { Archivo, Anton } from "next/font/google";
import "./globals.css";

// Volt type system: Archivo carries the interface, Anton is the loud display
// face (titles, big numbers). Exposed as CSS vars consumed in globals.css.
const archivo = Archivo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-archivo",
  display: "swap",
});
const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
  display: "swap",
});
// Generated by scripts/generate-splash.mjs alongside the PNGs, so the markup
// can never reference a launch image that isn't on disk.
import splashImages from "../../public/splash/index.json";
import { ServiceWorkerRegistration } from "./sw-register";
import { ThemeProvider } from "@/components/ThemeProvider";
import { SessionProvider } from "@/components/SessionProvider";
import { OfflineBanner } from "@/components/ui/feedback";

export const metadata: Metadata = {
  title: "Kadenz",
  description: "Personal running training plan",
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Kadenz",
  },
  // Standard replacement for apple-mobile-web-app-capable (Android/standards).
  other: { "mobile-web-app-capable": "yes" },
  icons: {
    icon: [
      { url: "/mark.svg", type: "image/svg+xml" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

export const viewport: Viewport = {
  // Dynamically updated per active theme by ThemeProvider; light is the default.
  themeColor: "#F4F4EE",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Required for env(safe-area-inset-*) to resolve on notched iPhones.
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased light ${archivo.variable} ${anton.variable}`}>
      <head>
        <link rel="preconnect" href="https://api.open-meteo.com" />
        {/* iOS home-screen PWAs ignore the manifest splash, so the launch image
            is pinned per device resolution. Android uses background_color. */}
        {splashImages.map((s) => (
          <link key={s.href} rel="apple-touch-startup-image" media={s.media} href={s.href} />
        ))}
        <script dangerouslySetInnerHTML={{ __html: `
          try {
            var s = JSON.parse(localStorage.getItem('kadenz_settings') || '{}');
            var t = s.theme || 'light';
            if (t === 'dark' || (t === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches))
              document.documentElement.classList.remove('light');
          } catch(e) {}
        `}} />
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeProvider />
        <ServiceWorkerRegistration />
        <div className="app-frame">
          <OfflineBanner />
          <SessionProvider>{children}</SessionProvider>
        </div>
      </body>
    </html>
  );
}
